/**
 * The active brand, for the cloud.
 *
 * GENERATED by `pnpm brand <key>`. Edit packages/ui/src/brand/brands.ts.
 */
export const BRAND = {
  key: "arkom",
  productName: "Arkom POS",
  wordmark: "ARKOM",
  wordmarkSuffix: "POS",
  copyright: "© Codroon",
} as const;

/** Only Codroon ships a drawn wordmark; every other brand sets its name in type. */
export const HAS_WORDMARK_SVG = false;
